### ISSUE TITLE
Silent mode Support 

### ISSUE THREAD

**Issue by ghuiii** [Hentioe/policr#174]
Please support silent mode, which doesn’t disturb others

**Comment by Hentioe** [comment]
你指的是要求验证的提示消息静音吗？这值得考虑。如果你认为还有其它的消息需要静音，可以说出来。

**Comment by ghuiii** [comment]
是的，其他人需要知道的消息都可以静音，slient mode是telegram的新功能

**Comment by Hentioe** [comment]
好的 感谢补充。这个功能很快就会实现。

**Comment by ghuiii** [comment]
@Hentioe 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/5203798/63639357-b9868000-c6c4-11e9-9ee7-62a25cb977d4.png">

这条消息不支持自己删除吗？

**Comment by Hentioe** [comment]
@ghuiii 支持的。使用 `/clean_mode` 指令可以配置。

**Comment by ghuiii** [comment]
我配置了，但应该是在这条消息之后设置的

**Comment by Hentioe** [comment]
配置前的消息需要自己手动删除。

**Comment by ghuiii** [comment]
@Hentioe 感谢你的工作，另外再提个建议，验证失败的处理能不能调整一下，像 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/5203798/63639539-02d7cf00-c6c7-11e9-8598-7e543dca550d.png">
失败后自动封禁一段时间而不是永远封禁。我现在理解Policr是永远封禁吧

截图的bot是 https://github.com/jqs7/zwei

**Comment by Hentioe** [comment]
是的。如果不想封禁，可以将倒计时调整为无限，这样就只会禁言用户。如果不想永久保留验证消息，也可以将验证时间设置为几个小时甚至更长。将人封禁以后又解除，实际上只会照顾到极其少数的纯小白用户，这些用户可能连验证是什么概念都不知道。并且不这么做的主要原因是和某些验证方式冲突，例如自定义验证，只要反复进几次就能猜中答案了。

**Comment by Hentioe** [comment]
现在 `/settings` 指令中多了一个「静音模式」可以启用。启用以后大部分消息发出来都没有声音通知，排除私聊消息（私聊消息不影响其他人）。
