### ISSUE TITLE
新功能：只有加入对应的频道才能进群

### ISSUE THREAD

**Issue by wulimaxh** [Hentioe/policr#198]
rt
判断用户是否加入与group绑定的channel，如果已经加入频道，点击unlock后可以解封。

**Comment by Hentioe** [comment]
为什么要解锁？你指的是进群后验证失败吗？

**Comment by wulimaxh** [comment]
看来我没描述清楚。
我指的是用户第一次加入群，在群验证的时候提示他要先加入频道，才可以解封。
通常情况下是：用户进去完成问题验证就可以了；新需求是：问题提示为让他加入频道，加入频道后再在群里完成问题验证才可以进群；换句话说就是保证每一个进群的人都是加入过频道的。绑定关系

**Comment by Hentioe** [comment]
这在我看到是非常少见的需求，包括我个人都不会有这种要求。我建议你把频道链接放在欢迎消息中，推荐使用 `-b [关注频道](频道链接)` 在欢迎消息中的带上指向频道的按钮。

**Comment by wulimaxh** [comment]
我是这么做的，但是这样子用户加频道的人会非常少，可能是群人数的一半都不到，导致频道发一些通知有一半人不能及时看到；我是看到别的群有这么用的，感觉效果非常好，他们群人数和频道人数基本一致。

**Comment by Hentioe** [comment]
有待考虑，暂时关闭。
