### ISSUE TITLE
Crystal 二进制是否是 `static` 的呀？

### ISSUE THREAD

**Issue by Jamlee** [Hentioe/policr#228]
据目前了解到它的静态二进制编译貌似只是适合alphine这类musl glibc系统的。其他貌似也能用，但是理论上不是完美支持的。大师能传道一下不？看到有说到发布的问题 我也很关注

**Comment by Hentioe** [comment]
你的调查是正确的，当前它的标准库实现使用了一些 C 库，所以理论上不存在纯 Crystal 程序。我的服务端 Crystal 程序通常跑在 Debian 上，例如这个以 Deiban 作为基础镜像的 Dockerfile 中写了必须安装的依赖：https://github.com/Hentioe/dockerfiles/blob/master/crystal/runtime-slim/Dockerfile

Alpine 上可以静态编译，不过我没试过。毕竟我也不在乎那一点大小……

**Comment by Jamlee** [comment]
是的。我对比过 swift 和 crystal ，实际上 swift 也可以实现类似 crystal 的静态编译。无法实现像go那种全静态的部署。希望它们越发展越方便，这样丢个二进制加一个配置文件给人就万事大吉。
