### ISSUE TITLE
[错别字] "您正在设置来源调, 一个具体的例子"

### ISSUE THREAD

**Issue by XyLyXyRR** [Hentioe/policr#236]
![oBkCH4TzROSENZsYSDiTg8gW.jpg](https://i.loli.net/2019/11/01/hN3qoXTH1OkKze7.jpg)

**Comment by Hentioe** [comment]
是的，曾经有人反馈过，我给忘了。谢谢提醒。相关修正提交以后此 Issue 将自动关闭。

**Comment by XyLyXyRR** [comment]
![Screenshot_2019-11-03-22-47-53-985_org.thunderdog.challegram.jpg](https://i.loli.net/2019/11/03/1cNXm75nD8bMz9P.jpg)

为什么我总能看见错别字....

"通过验证"应该在"的时间"后面吧?

**Comment by Hentioe** [comment]
不好意思没注意你后续回复。在我看来这两种都可以。

1. 请回答问题 1 + 1 = ? （以）通过验证，你有 60 秒的时间
1. 请回答问题 1 + 1 = ? （，）你有 60 秒的时间通过验证

实际上我写的是第一种，只不过可能缺少了一个以字。通过验证放在后面中间就要加一个逗号。当然这种地方确实需要严格一些，因为很多群直接照抄例子中的内容或产生误解。

**Comment by XyLyXyRR** [comment]
哇, 我都不知道我语言这么差的. 这种语法正确却不常见的用法, 我最近碰见好几次.  o(╥﹏╥)o

感谢回复.
