### ISSUE TITLE
api无效

### ISSUE THREAD

**Issue by steamsv** [Hentioe/policr#253]
ERROR: Invalid interpolation format for "environment" option in service "server": 

别的程序上该api有效

**Comment by Hentioe** [comment]
能具体一点你干什么提示了这个错误吗？

**Comment by steamsv** [comment]
POLICR_BOT_TOKEN: "${api}"
当我git clone下来后，部署完环境，填入相关信息后，直接运行docker-compose up -d，会报api无效的错误，也就是以上的错误

**Comment by Hentioe** [comment]
你能把 `docker-compose.yml` 贴出来吗？敏感信息去掉。然后把 docker-componse 的版本发出来。

**Comment by Hentioe** [comment]
当前不建议部署此项目。可转向 [policr-mini](https://github.com/Hentioe/policr-mini) 交流。
